package user_repo

var dummyData = []UserRepo{
	{
		id: "id1", Name: "react", Status: "indexed", LastIndexed: "1746", TotalLibs: "42", 
		Description: "RAG pipeline for semantic search over GitHub issues. Built with Java, Spring Boot, and OpenSearch.",
		Libraries: []LibraryStatus{
			{name: "axios",       version: "v1.7.2",   status: "healthy"},
			{name: "lodash",      version: "v4.17.21", status: "deprecated"},
			{name: "moment",      version: "v2.29.4",  status: "archived"},
			{name: "react-query", version: "v5.28.0",  status: "healthy"},
			{name: "classnames",  version: "v2.3.2",   status: "healthy"},
			{name: "prop-types",  version: "v15.8.1",  status: "deprecated"},
			{name: "redux",       version: "v4.2.1",   status: "healthy"},
		},
	},
	{
		id: "id2", Name: "next.js", Status: "indexed", LastIndexed: "1745", TotalLibs: "3",
		Description: "RAG pipeline for semantic search over GitHub issues. Built with Java, Spring Boot, and OpenSearch.",
		Libraries: []LibraryStatus{
			{name: "zod",      version: "v3.22.4", status: "healthy"},
			{name: "immer",    version: "v10.0.3", status: "healthy"},
			{name: "date-fns", version: "v2.30.0", status: "deprecated"},
		},
	},
	{
		id: "id3", Name: "tailwindcss", Status: "pending", LastIndexed: "0", TotalLibs: "9",
		Description: "RAG pipeline for semantic search over GitHub issues. Built with Java, Spring Boot, and OpenSearch.",
		Libraries: []LibraryStatus{
			{name: "express",      version: "v4.19.2", status: "healthy"},
			{name: "dotenv",       version: "v16.4.5", status: "healthy"},
			{name: "cors",         version: "v2.8.5",  status: "healthy"},
			{name: "helmet",       version: "v7.1.0",  status: "healthy"},
			{name: "morgan",       version: "v1.10.0", status: "deprecated"},
			{name: "body-parser",  version: "v1.20.2", status: "archived"},
			{name: "jsonwebtoken", version: "v9.0.2",  status: "healthy"},
			{name: "bcrypt",       version: "v5.1.1",  status: "healthy"},
			{name: "multer",       version: "v1.4.5",  status: "deprecated"},
		},
	},
	{
		id: "id4", Name: "vue", Status: "indexed", LastIndexed: "1746", TotalLibs: "5",
		Description: "RAG pipeline for semantic search over GitHub issues. Built with Java, Spring Boot, and OpenSearch.",
		Libraries: []LibraryStatus{
			{name: "pinia",        version: "v2.1.7",  status: "healthy"},
			{name: "vue-router",   version: "v4.3.0",  status: "healthy"},
			{name: "vuelidate",    version: "v2.0.3",  status: "deprecated"},
			{name: "vue-i18n",     version: "v9.10.2", status: "healthy"},
			{name: "vuex",         version: "v4.1.0",  status: "archived"},
		},
	},
	{
		id: "id5", Name: "svelte", Status: "indexed", LastIndexed: "1745", TotalLibs: "7",
		Description: "RAG pipeline for semantic search over GitHub issues. Built with Java, Spring Boot, and OpenSearch.",
		Libraries: []LibraryStatus{
			{name: "svelte-kit",     version: "v2.5.7",  status: "healthy"},
			{name: "svelte-query",   version: "v5.0.0",  status: "healthy"},
			{name: "svelte-forms",   version: "v1.3.2",  status: "deprecated"},
			{name: "svelte-motion",  version: "v0.12.2", status: "archived"},
			{name: "svelte-i18n",    version: "v3.7.4",  status: "healthy"},
			{name: "svelte-persist", version: "v1.1.0",  status: "deprecated"},
			{name: "svelte-meta",    version: "v0.5.1",  status: "healthy"},
		},
	},
	{
		id: "id6", Name: "angular", Status: "pending", LastIndexed: "0", TotalLibs: "4",
		Description: "RAG pipeline for semantic search over GitHub issues. Built with Java, Spring Boot, and OpenSearch.",
		Libraries: []LibraryStatus{
			{name: "rxjs",          version: "v7.8.1",  status: "healthy"},
			{name: "ngrx",          version: "v17.2.0", status: "healthy"},
			{name: "angular-forms", version: "v16.0.0", status: "archived"},
			{name: "zone.js",       version: "v0.14.4", status: "deprecated"},
		},
	},
	{
		id: "id7", Name: "remix", Status: "indexed", LastIndexed: "1746", TotalLibs: "6",
		Description: "RAG pipeline for semantic search over GitHub issues. Built with Java, Spring Boot, and OpenSearch.",
		Libraries: []LibraryStatus{
			{name: "prisma",       version: "v5.13.0", status: "healthy"},
			{name: "zod",          version: "v3.22.4", status: "healthy"},
			{name: "tailwindcss",  version: "v3.4.3",  status: "healthy"},
			{name: "conform",      version: "v1.1.1",  status: "healthy"},
			{name: "remix-auth",   version: "v3.6.0",  status: "deprecated"},
			{name: "react-hot-toast", version: "v2.4.1", status: "archived"},
		},
	},
	{
		id: "id8", Name: "astro", Status: "indexed", LastIndexed: "1745", TotalLibs: "3",
		Description: "RAG pipeline for semantic search over GitHub issues. Built with Java, Spring Boot, and OpenSearch.",
		Libraries: []LibraryStatus{
			{name: "sharp",       version: "v0.33.3", status: "healthy"},
			{name: "mdx",         version: "v3.1.0",  status: "healthy"},
			{name: "nanostores", version: "v0.10.3", status: "deprecated"},
		},
	},
	{
		id: "id9", Name: "nuxt", Status: "pending", LastIndexed: "0", TotalLibs: "8",
		Description: "RAG pipeline for semantic search over GitHub issues. Built with Java, Spring Boot, and OpenSearch.",
		Libraries: []LibraryStatus{
			{name: "pinia",        version: "v2.1.7",  status: "healthy"},
			{name: "vee-validate",  version: "v4.12.8", status: "deprecated"},
			{name: "nuxt-auth",    version: "v0.6.7",  status: "archived"},
			{name: "nuxt-i18n",    version: "v8.3.1",  status: "healthy"},
			{name: "nuxt-image",   version: "v1.7.0",  status: "healthy"},
			{name: "nuxt-content", version: "v2.12.1", status: "healthy"},
			{name: "vueuse",       version: "v10.9.0", status: "healthy"},
			{name: "ofetch",       version: "v1.3.4",  status: "deprecated"},
		},
	},
	{
		id: "id10", Name: "solid-js", Status: "indexed", LastIndexed: "1746", TotalLibs: "5",
		Description: "RAG pipeline for semantic search over GitHub issues. Built with Java, Spring Boot, and OpenSearch.",
		Libraries: []LibraryStatus{
			{name: "solid-router",  version: "v0.13.6", status: "healthy"},
			{name: "solid-query",   version: "v5.28.0", status: "healthy"},
			{name: "solid-forms",   version: "v0.4.2",  status: "deprecated"},
			{name: "modular-forms", version: "v0.22.1", status: "healthy"},
			{name: "solid-dnd",     version: "v0.7.4",  status: "archived"},
		},
	},
	{
		id: "id11", Name: "qwik", Status: "indexed", LastIndexed: "1745", TotalLibs: "7",
		Description: "RAG pipeline for semantic search over GitHub issues. Built with Java, Spring Boot, and OpenSearch.",
		Libraries: []LibraryStatus{
			{name: "qwik-city",    version: "v1.5.5",  status: "healthy"},
			{name: "builder.io",   version: "v2.0.1",  status: "deprecated"},
			{name: "partytown",    version: "v0.10.2", status: "archived"},
			{name: "mitosis",      version: "v0.4.6",  status: "healthy"},
			{name: "qwik-speak",   version: "v1.1.0",  status: "healthy"},
			{name: "vite-plugin-qwik", version: "v1.5.5", status: "healthy"},
			{name: "qwik-auth",    version: "v0.2.0",  status: "deprecated"},
		},
	},
	{
		id: "id12", Name: "preact", Status: "pending", LastIndexed: "0", TotalLibs: "4",
		Description: "RAG pipeline for semantic search over GitHub issues. Built with Java, Spring Boot, and OpenSearch.",
		Libraries: []LibraryStatus{
			{name: "preact-router",  version: "v4.1.2",  status: "archived"},
			{name: "preact-signals", version: "v1.2.3",  status: "healthy"},
			{name: "preact-iso",     version: "v2.6.2",  status: "healthy"},
			{name: "htm",            version: "v3.1.1",  status: "deprecated"},
		},
	},
	{
		id: "id13", Name: "lit", Status: "indexed", LastIndexed: "1746", TotalLibs: "6",
		Description: "RAG pipeline for semantic search over GitHub issues. Built with Java, Spring Boot, and OpenSearch.",
		Libraries: []LibraryStatus{
			{name: "lit-html",     version: "v3.1.3",  status: "healthy"},
			{name: "lit-element",  version: "v4.0.4",  status: "healthy"},
			{name: "haunted",      version: "v4.8.1",  status: "archived"},
			{name: "shoelace",     version: "v2.15.0", status: "healthy"},
			{name: "lion",         version: "v0.18.0", status: "deprecated"},
			{name: "wired-elements", version: "v2.0.6", status: "archived"},
		},
	},
	{
		id: "id14", Name: "ember", Status: "indexed", LastIndexed: "1745", TotalLibs: "3",
		Description: "RAG pipeline for semantic search over GitHub issues. Built with Java, Spring Boot, and OpenSearch.",
		Libraries: []LibraryStatus{
			{name: "ember-data",    version: "v5.3.1",  status: "deprecated"},
			{name: "ember-simple-auth", version: "v6.0.0", status: "archived"},
			{name: "ember-cli-mirage", version: "v3.0.4", status: "archived"},
		},
	},
	{
		id: "id15", Name: "alpine", Status: "pending", LastIndexed: "0", TotalLibs: "5",
		Description: "RAG pipeline for semantic search over GitHub issues. Built with Java, Spring Boot, and OpenSearch.",
		Libraries: []LibraryStatus{
			{name: "alpinejs",    version: "v3.13.10", status: "healthy"},
			{name: "alpine-ajax", version: "v0.12.0",  status: "healthy"},
			{name: "alpine-magic-helpers", version: "v0.9.0", status: "archived"},
			{name: "pikaday",     version: "v1.8.2",   status: "deprecated"},
			{name: "sweetalert2", version: "v11.10.8", status: "healthy"},
		},
	},
}
